export const mockSearchResults21 = {
  content: [
    {
      id: '1',
      titulo: 'Livro 1',
      autores: [{ nome: 'Autor 1' }],
      editora: 'Editora 1',
      numeroDePaginas: 10,
      anoDePublicacao: '1910',
      capaUrl: '/img1.png',
    },
    {
      id: '2',
      titulo: 'Livro 2',
      autores: [{ nome: 'Autor 2' }],
      editora: 'Editora 2',
      numeroDePaginas: 20,
      anoDePublicacao: '1920',
      capaUrl: '/img1.png',
    },
    {
      id: '3',
      titulo: 'Livro 3',
      autores: [{ nome: 'Autor 3' }],
      editora: 'Editora 1',
      numeroDePaginas: 30,
      anoDePublicacao: '1930',
      capaUrl: null,
    },
    {
      id: '4',
      titulo: 'Livro 4',
      autores: [{ nome: 'Autor 4' }],
      editora: 'Editora 2',
      numeroDePaginas: 40,
      anoDePublicacao: '1940',
      capaUrl: '/img1.png',
    },
    {
      id: '5',
      titulo: 'Livro 5',
      autores: [{ nome: 'Autor 5' }],
      editora: 'Editora 1',
      numeroDePaginas: 50,
      anoDePublicacao: '1950',
      capaUrl: '/img1.png',
    },
    {
      id: '6',
      titulo: 'Livro 6',
      autores: [{ nome: 'Autor 6' }],
      editora: 'Editora 2',
      numeroDePaginas: 60,
      anoDePublicacao: '1960',
      capaUrl: '/img1.png',
    },
    {
      id: '7',
      titulo: 'Livro 7',
      autores: [{ nome: 'Autor 7' }],
      editora: 'Editora 1',
      numeroDePaginas: 70,
      anoDePublicacao: '1970',
      capaUrl: '/img1.png',
    },
    {
      id: '8',
      titulo: 'Livro 8',
      autores: [{ nome: 'Autor 8' }],
      editora: 'Editora 2',
      numeroDePaginas: 80,
      anoDePublicacao: '1980',
      capaUrl: '/img1.png',
    },
    {
      id: '9',
      titulo: 'Livro 9',
      autores: [{ nome: 'Autor 9' }],
      editora: 'Editora 1',
      numeroDePaginas: 90,
      anoDePublicacao: '1990',
      capaUrl: '/img1.png',
    },
    {
      id: '10',
      titulo: 'Livro 10',
      autores: [{ nome: 'Autor 10' }],
      editora: 'Editora 2',
      numeroDePaginas: 100,
      anoDePublicacao: '2000',
      capaUrl: '/img1.png',
    },
    {
      id: '11',
      titulo: 'Livro 11',
      autores: [{ nome: 'Autor 11' }],
      editora: 'Editora 1',
      numeroDePaginas: 110,
      anoDePublicacao: '2001',
      capaUrl: '/img1.png',
    },
    {
      id: '12',
      titulo: 'Livro 12',
      autores: [{ nome: 'Autor 12' }],
      editora: 'Editora 2',
      numeroDePaginas: 120,
      anoDePublicacao: '2002',
      capaUrl: '/img1.png',
    },
    {
      id: '13',
      titulo: 'Livro 13',
      autores: [{ nome: 'Autor 13' }],
      editora: 'Editora 1',
      numeroDePaginas: 130,
      anoDePublicacao: '2003',
      capaUrl: '/img1.png',
    },
    {
      id: '14',
      titulo: 'Livro 14',
      autores: [{ nome: 'Autor 14' }],
      editora: 'Editora 2',
      numeroDePaginas: 140,
      anoDePublicacao: '2004',
      capaUrl: '/img1.png',
    },
    {
      id: '15',
      titulo: 'Livro 15',
      autores: [{ nome: 'Autor 15' }],
      editora: 'Editora 1',
      numeroDePaginas: 150,
      anoDePublicacao: '2005',
      capaUrl: '/img1.png',
    },
    {
      id: '16',
      titulo: 'Livro 16',
      autores: [{ nome: 'Autor 16' }],
      editora: 'Editora 2',
      numeroDePaginas: 160,
      anoDePublicacao: '2006',
      capaUrl: '/img1.png',
    },
    {
      id: '17',
      titulo: 'Livro 17',
      autores: [{ nome: 'Autor 17' }],
      editora: 'Editora 1',
      numeroDePaginas: 170,
      anoDePublicacao: '2007',
      capaUrl: '/img1.png',
    },
    {
      id: '18',
      titulo: 'Livro 18',
      autores: [{ nome: 'Autor 18' }],
      editora: 'Editora 2',
      numeroDePaginas: 180,
      anoDePublicacao: '2008',
      capaUrl: '/img1.png',
    },
    {
      id: '19',
      titulo: 'Livro 19',
      autores: [{ nome: 'Autor 19' }],
      editora: 'Editora 1',
      numeroDePaginas: 190,
      anoDePublicacao: '2009',
      capaUrl: '/img1.png',
    },
    {
      id: '20',
      titulo: 'Livro 20',
      autores: [{ nome: 'Autor 20' }],
      editora: 'Editora 2',
      numeroDePaginas: 200,
      anoDePublicacao: '2010',
      capaUrl: '/img1.png',
    },
    {
      id: '21',
      titulo: 'Livro 21',
      autores: [{ nome: 'Autor 21' }],
      editora: 'Editora 1',
      numeroDePaginas: 210,
      anoDePublicacao: '2011',
      capaUrl: '/img1.png',
    },
  ],
  totalElements: 21,
  totalPages: 2,
};
