export enum IdiomaEnum {
  PORTUGUES = 'PORTUGUES',
  INGLES = 'INGLES',
  ESPANHOL = 'ESPANHOL',
  FRANCES = 'FRANCES',
  ALEMAO = 'ALEMAO',
  ITALIANO = 'ITALIANO',
  JAPONES = 'JAPONES',
  CHINES = 'CHINES',
  COREANO = 'COREANO',
  ARABE = 'ARABE',
  RUSSO = 'RUSSO',
  HINDI = 'HINDI',
  HOLANDES = 'HOLANDES',
  SUECO = 'SUECO',
  DINAMARQUES = 'DINAMARQUES',
  FINLANDES = 'FINLANDES',
  NORUEGUES = 'NORUEGUES',
  POLONES = 'POLONES',
  TURCO = 'TURCO',
  GREGO = 'GREGO',
  HEBRAICO = 'HEBRAICO',
  TAILANDES = 'TAILANDES',
  VIETNAMITA = 'VIETNAMITA',
  INDONESIO = 'INDONESIO',
  UCRANIANO = 'UCRANIANO',
  TCHECO = 'TCHECO',
  HUNGARO = 'HUNGARO',
}

export const LIVRO_IDIOMA_LABEL: Record<IdiomaEnum, string> = {
  [IdiomaEnum.PORTUGUES]: 'Português',
  [IdiomaEnum.INGLES]: 'Inglês',
  [IdiomaEnum.ESPANHOL]: 'Espanhol',
  [IdiomaEnum.FRANCES]: 'Francês',
  [IdiomaEnum.ALEMAO]: 'Alemão',
  [IdiomaEnum.ITALIANO]: 'Italiano',
  [IdiomaEnum.JAPONES]: 'Japonês',
  [IdiomaEnum.CHINES]: 'Chinês',
  [IdiomaEnum.COREANO]: 'Coreano',
  [IdiomaEnum.ARABE]: 'Árabe',
  [IdiomaEnum.RUSSO]: 'Russo',
  [IdiomaEnum.HINDI]: 'Hindi',
  [IdiomaEnum.HOLANDES]: 'Holandês',
  [IdiomaEnum.SUECO]: 'Sueco',
  [IdiomaEnum.DINAMARQUES]: 'Dinamarquês',
  [IdiomaEnum.FINLANDES]: 'Finlandês',
  [IdiomaEnum.NORUEGUES]: 'Norueguês',
  [IdiomaEnum.POLONES]: 'Polonês',
  [IdiomaEnum.TURCO]: 'Turco',
  [IdiomaEnum.GREGO]: 'Grego',
  [IdiomaEnum.HEBRAICO]: 'Hebraico',
  [IdiomaEnum.TAILANDES]: 'Tailandês',
  [IdiomaEnum.VIETNAMITA]: 'Vietnamita',
  [IdiomaEnum.INDONESIO]: 'Indonésio',
  [IdiomaEnum.UCRANIANO]: 'Ucraniano',
  [IdiomaEnum.TCHECO]: 'Tcheco',
  [IdiomaEnum.HUNGARO]: 'Húngaro',
};

export const LIVRO_IDIOMA_OPCOES = Object.entries(LIVRO_IDIOMA_LABEL).map(
  ([key, label]) => ({
    valorEnum: key as IdiomaEnum,
    label,
  })
);
