export const mockPopularBooks5 = {
  content: [
    {
      id: '1',
      titulo: 'Livro 1',
      autores: [{ nome: 'Autor 1' }],
      editora: 'Editora 1',
      numeroDePaginas: 10,
      anoDePublicacao: '1910',
      capaUrl: '/img1.png',
    },
    {
      id: '2',
      titulo: 'Livro 2',
      autores: [{ nome: 'Autor 2' }],
      editora: 'Editora 2',
      numeroDePaginas: 20,
      anoDePublicacao: '1920',
      capaUrl: '/img1.png',
    },
    {
      id: '3',
      titulo: 'Livro 3',
      autores: [{ nome: 'Autor 3' }],
      editora: 'Editora 1',
      numeroDePaginas: 30,
      anoDePublicacao: '1930',
      capaUrl: null,
    },
    {
      id: '4',
      titulo: 'Livro 4',
      autores: [{ nome: 'Autor 4' }],
      editora: 'Editora 2',
      numeroDePaginas: 40,
      anoDePublicacao: '1940',
      capaUrl: '/img1.png',
    },
    {
      id: '5',
      titulo: 'Livro 5',
      autores: [{ nome: 'Autor 5' }],
      editora: 'Editora 1',
      numeroDePaginas: 50,
      anoDePublicacao: '1950',
      capaUrl: '/img1.png',
    },
  ],
  totalElements: 5,
  totalPages: 2,
};
